name: Trufflehog Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Install Trufflehog
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
          trufflehog --version


      - name: Run Trufflehog Scan
        run: |
          trufflehog filesystem . --json > trufflehog-results.json


      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-results
          path: trufflehog-results.json


      - name: Upload to AccuKnox
        env:
          TOKEN: ${{ secrets.TOKEN }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
        run: |
          curl --location --request POST "https://cspm.dev.accuknox.com/api/v1/artifact/?tenant_id=${{ env.TENANT_ID }}&data_type=TruffleHog&save_to_s3=false&label_id=trufflehog" \
          --header "Tenant-Id: ${{ env.TENANT_ID }}" \
          --header "Authorization: Bearer ${{ env.TOKEN }}" \
          --form "file=@./trufflehog-results.json"
